# Generated by Django 5.0.6 on 2024-05-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sessionName", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "sessionIntro",
                    models.TextField(blank=True, max_length=200, null=True),
                ),
                ("part", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
