# Generated by Django 5.0.6 on 2024-05-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teamName", models.CharField(max_length=10)),
                (
                    "projectType",
                    models.CharField(
                        choices=[
                            ("미니프로젝트", "미니프로젝트"),
                            ("해커톤프로젝트", "해커톤프로젝트"),
                            ("개인프로젝트", "개인프로젝트"),
                        ],
                        default="미니프로젝트",
                        max_length=200,
                    ),
                ),
                ("projectDetail", models.TextField(max_length=200)),
                (
                    "projectImage",
                    models.ImageField(
                        blank=True,
                        default="project_photos/default.jpg",
                        null=True,
                        upload_to="project_photos/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
