# Generated by Django 5.0.6 on 2024-05-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="projectImage",
            field=models.ImageField(
                blank=True,
                default="project_photos/default.png",
                null=True,
                upload_to="project_photos/",
            ),
        ),
    ]
