# Generated by Django 5.0.6 on 2024-05-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("memberId", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("studentNumber", models.IntegerField()),
                ("currentPosition", models.CharField(max_length=4)),
                (
                    "userPhoto",
                    models.ImageField(
                        blank=True,
                        default="member_photos/default.jpg",
                        null=True,
                        upload_to="member_photos/",
                    ),
                ),
                ("year", models.IntegerField()),
                ("introduction", models.TextField(max_length=100)),
                ("part", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
