# Generated by Django 5.0.6 on 2024-05-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="userPhoto",
            field=models.ImageField(
                blank=True,
                default="member_photos/default.png",
                null=True,
                upload_to="member_photos/",
            ),
        ),
    ]
